namespace Scmos.Api.Data;

/// <summary>
/// A report as it read on the day it was taken.
///
/// <para>
/// The point of keeping these is not convenience — the report can be rebuilt
/// from the register at any time. It is that <b>rebuilding it later gives a
/// different answer</b>. Arrival times are keyed in days or weeks after the
/// trip, so a month regenerated in December is measured over more trips than
/// the same month regenerated on the first of October, and the on-time rate
/// moves with it. Both figures are correct; they are answers to different
/// questions.
/// </para>
///
/// <para>
/// A customer holding a report that says 88% and a system that now says 91% is
/// an argument nobody can settle without this table. So the whole computed
/// document is stored as it stood, and the screen renders the stored figures
/// rather than recomputing them.
/// </para>
/// </summary>
public class ReportArchiveEntry
{
    public long Id { get; set; }

    /// <summary>The customer as the register spelled it that day.</summary>
    public string Customer { get; set; } = "";

    /// <summary>MM/yyyy, the month reported on.</summary>
    public string Month { get; set; } = "";

    /// <summary>When the snapshot was taken.</summary>
    public DateTimeOffset TakenAt { get; set; }

    /// <summary>
    /// Who asked for it — an operator's signature, or "scheduler" when the
    /// month rolled over on its own. Worth distinguishing: a figure somebody
    /// generated by hand in the middle of a month and one the system took at
    /// the close of it are not equally quotable.
    /// </summary>
    public string TakenBy { get; set; } = "";

    /// <summary>The whole computed report, exactly as the API answered it.</summary>
    public string Document { get; set; } = "";

    /* ---- promoted so the list can be read without parsing every document ---- */

    public int Trips { get; set; }

    /// <summary>How many of those could be judged at all.</summary>
    public int Measurable { get; set; }

    /// <summary>
    /// The on-time rate, or null when nothing could be measured.
    ///
    /// Nullable in the column as well as in the rule. A zero here would make
    /// every unmeasured month sort as the worst month on record.
    /// </summary>
    public double? Otd { get; set; }
}
